// <auto-generated />
using System;
using Food_Store.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Food_Store.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20181210090856_addAuth")]
    partial class addAuth
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Food_Store.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("Path");

                    b.Property<double>("Price");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Food_Store.Models.ItemType", b =>
                {
                    b.Property<Guid>("ItemId");

                    b.Property<Guid>("ItTypeId");

                    b.HasKey("ItemId", "ItTypeId");

                    b.HasIndex("ItTypeId");

                    b.ToTable("itemTypes");
                });

            modelBuilder.Entity("Food_Store.Models.ItType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("Food_Store.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Food_Store.Models.ItemType", b =>
                {
                    b.HasOne("Food_Store.Models.ItType", "Type")
                        .WithMany("ItemType")
                        .HasForeignKey("ItTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Food_Store.Models.Item", "Item")
                        .WithMany("ItemType")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
