// <auto-generated />
using System;
using Food_Store.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Food_Store.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20181211213009_updateUserItems")]
    partial class updateUserItems
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Food_Store.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("Path");

                    b.Property<double>("Price");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Food_Store.Models.ItemType", b =>
                {
                    b.Property<Guid>("ItemId");

                    b.Property<Guid>("ItTypeId");

                    b.HasKey("ItemId", "ItTypeId");

                    b.HasIndex("ItTypeId");

                    b.ToTable("itemTypes");
                });

            modelBuilder.Entity("Food_Store.Models.ItType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("Food_Store.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new { Id = new Guid("3e134d8d-b208-4a36-a4b6-732d06756907"), Name = "admin" },
                        new { Id = new Guid("dbd077aa-7215-4b8f-a2a3-5feca43817fb"), Name = "user" }
                    );
                });

            modelBuilder.Entity("Food_Store.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Password");

                    b.Property<Guid?>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new { Id = new Guid("5334cf34-29aa-412b-8a1e-0a8d6c488cc8"), Email = "admin@mail.ru", Password = "123456", RoleId = new Guid("3e134d8d-b208-4a36-a4b6-732d06756907") }
                    );
                });

            modelBuilder.Entity("Food_Store.Models.UsersItems", b =>
                {
                    b.Property<Guid>("ItemId");

                    b.Property<Guid>("UserId");

                    b.Property<double>("Amount");

                    b.HasKey("ItemId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersItems");
                });

            modelBuilder.Entity("Food_Store.Models.ItemType", b =>
                {
                    b.HasOne("Food_Store.Models.ItType", "Type")
                        .WithMany("ItemType")
                        .HasForeignKey("ItTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Food_Store.Models.Item", "Item")
                        .WithMany("ItemType")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Food_Store.Models.User", b =>
                {
                    b.HasOne("Food_Store.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");
                });

            modelBuilder.Entity("Food_Store.Models.UsersItems", b =>
                {
                    b.HasOne("Food_Store.Models.Item", "Item")
                        .WithMany("UsersItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Food_Store.Models.User", "User")
                        .WithMany("UsersItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
